version: '3'
services:
    nginx:
        container_name: nginx-laravel9-boilerplate
        image: nginx:latest
        command: [ "nginx", "-g", "daemon off;" ]
        depends_on:
            - app
        links:
            - app
        working_dir: /var/www/html
        volumes:
            - ./docker/nginx/asset/:/etc/nginx/conf.d/
            - ./docker/nginx/log:/var/log/nginx/:rw
            - ./:/var/www/html:rw
        env_file:
            - ./docker/.env
        ports:
            - "${DOCKER_NGINX_PORT:-8080}:80"
        logging:
            options:
                max-size: "1m"
                max-file: "3"
    app:
        container_name: app-laravel9-boilerplate
        build: ./docker/php
        links:
            - db
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:rw
    db:
        container_name: db-laravel9-boilerplate
        image: "mysql:latest"
        volumes:
            - "./dbdata:/var/lib/mysql/"
        env_file:
            - ./docker/.env
        ports:
            - "${DOCKER_DB_PORT:-3307}:3306"
    phpmyadmin:
        container_name: phpmyadmin-laravel9-boilerplate
        image: phpmyadmin/phpmyadmin
        env_file:
            - ./docker/.env
        ports:
            - "${DOCKER_DB_PANEL_PORT:-8082}:80"
        volumes:
            - /sessions
